### ISSUE TITLE
Doesn't build on Mac OSX 10.11.6

### ISSUE THREAD

**Issue by m-bob** [statebox/idris-ct#45] opened 2019-08-31 21:59 UTC
Using Elba. 27 libraries compiled successfully.

Then got error:

Couldn't build library target for statebox/idris-ct 0.1.0 (dir+/Users/murray/apps/idris-ct-master)
> "idris" "--check" "-p" "contrib" "Idris/FunctorAsCFunctor.lidr"
./Idris/FunctorAsCFunctor.lidr:45:27-78:
   |
45 | > functorPreserveId _ a = funExt (\x => functorIdentity {a} id (\v => Refl) x)
   |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
When checking right hand side of functorPreserveId with expected type
        functorOnMorphisms func a a (extIdentity a) = extIdentity (f a)

When checking an application of Idris.TypesAsCategoryExtensional.funExt:
        Type mismatch between
                map id x = id x (Type of functorIdentity x)
        and
                _ -> _ (Is functorIdentity x applied to too many arguments?)

        Specifically:
                Type mismatch between
                        (=) map id x
                and
                        \uv => _ -> uv

error: one or more packages couldn't be built

______________________________

Any ideas?

**Comment by clayrat** [comment] 2019-09-02 11:22
Which Idris version are you using?

**Comment by m-bob** [comment] 2019-09-02 18:35
Thanks for the reply! I should have thought of that. I'm using Idris 1.2.0.
I hadn't realized there is a newer version. Should I upgrade?

Thanks!

Murray

**Comment by clayrat** [comment] 2019-09-02 21:55
Yes, the definition of `functorIdentity` which we are relying on here has changed after 1.3.0. It's preferable to use the latest available version since there might be some other breaking changes.

**Comment by m-bob** [comment] 2019-09-02 22:42
Thanks! I cannot install idris 1.3.2 yet on my OS and I need to keep this
OS for awhile. I'll upgrade the OS as soon as I can.

In the meantime, I was able to install Idris 1.3.1 and got much farther,
but it still failed. Here's what I got:
...
Compiling Monoid.MonoidsCategory [statebox/idris-ct]
   Compiling MonoidalCategory.MonoidalCategory [statebox/idris-ct]
   Compiling MonoidalCategory.MonoidalCategoryHelpers [statebox/idris-ct]
   Compiling MonoidalCategory.StrictMonoidalCategory [statebox/idris-ct]
   Compiling MonoidalCategory.SymmetricMonoidalCategory [statebox/idris-ct]
   Compiling MonoidalCategory.SymmetricMonoidalCategoryHelpers
[statebox/idris-ct]
   Compiling PointedTypes.PointedTypesAsCategory [statebox/idris-ct]
   Compiling Preorder.MonotoneMap [statebox/idris-ct]
   Compiling Preorder.MonotoneMapAsFunctor [statebox/idris-ct]
   Compiling Preorder.PreorderAsCategory [statebox/idris-ct]
   Compiling Preorder.UniquePreorder [statebox/idris-ct]
   Compiling Product.ProductCategory [statebox/idris-ct]
   Compiling Product.ProductFunctor [statebox/idris-ct]
   Compiling CategoryReasoning [statebox/idris-ct]
   Compiling Utils [statebox/idris-ct]
     [error] Couldn't build library target for statebox/idris-ct 0.1.0
(dir+/Users/murray/apps/idris-ct-master)
Compiler is overloaded on compiling:
MonoidalCategory/SymmetricMonoidalCategoryHelpers.lidr

error: one or more packages couldn't be built

It seems peculiar that the error message is about a component which
apparently installed properly. It's trying to install 'Utils' but is
complaining about 'MonoidalCategory/SymmetricMonoidalCategoryHelpers' which
appears to have installed properly.

Should I wait until I can upgrade the OS and try again with Idris.1.3.2 ?

Or is there anything to do before then?

Thanks!

Murray

**Comment by marcosh** [comment] 2019-09-05 07:19
which Elba version are you using? The issue you mention is probably related
to https://github.com/elba/elba/issues/70

**Comment by m-bob** [comment] 2019-09-05 13:24
Thanks! I'm using Elba 0.3.1 -- which is the current binary release for OSX
(as of a couple of days ago).

Sounds like there are a few options. I can try again -- apparently the
combination sometimes works. I can try compiling directly with Idris. Or I
can try a different version of elba -- which means compiling elba from
source -- which means installing rust.

**Comment by clayrat** [comment] 2019-09-05 13:43
Please try compiling directly with Idris first, so we can see if the problem is only on Elba's side

**Comment by marcosh** [comment] 2019-09-05 13:48
I filed that issue on Elba on 0.3.1, so we may need to wait next release
for it to be solved. Anyway, try what Alex suggested to check if that is
actually the problem

**Comment by m-bob** [comment] 2019-09-06 04:24
Will do. It may take me a couple of days before I can get back to it though.
Thanks so much! I really appreciate the support!

**Comment by m-bob** [comment] 2019-09-07 16:51
Thank you!

Compiling with idris appears to have worked! I haven't tried using the
library yet but idris didn't complain when i ran "idris --checkpkg
idris-ct.ipkg"

Again, thanks!

**Comment by marcosh** [comment] 2019-09-08 13:03
@m-bob it seems that version 0.3.2 of Elba has been released (https://github.com/elba/elba/releases/tag/0.3.2), which should solve the above issue (I still haven't tried it, but it's definitely worth a shot)

**Comment by m-bob** [comment] 2019-09-08 15:09
Thanks -- I will when I can. Elba 3.0.2 is incompatible with the old
version of Mac OSX (10.11.6) that I need to use at present. (I just
realized I can try it on a different machine with a more recent OS. I'll
try it there.)

**Comment by marcosh** [comment] 2019-10-14 13:55
since the issue seems to be solved for now and there is no required work from our side at the moment, I'm closing this issue

**Closed by marcosh** 2019-10-14 13:55 UTC
